Name: streamlitDeploymentPipeline
SchemaVersion: "1.0"

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:
  InstallDependencies:
    Identifier: aws/lambda-invoke@v1
    Timeout: 10
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    Configuration:
      FunctionName: "install-dependencies"
      Payload: |
        {
          "commands": [
            "python -m venv .venv",
            "source .venv/bin/activate",
            "pip install -r requirements.txt"
          ]
        }

  CDKBootstrap:
    Identifier: aws/cdk-bootstrap@v1
    Timeout: 10
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      Region: us-east-1
    Environment:
      Name: default_environment
      Connections:
        - Name: "536697236057"
          Role: CodeCatalystWorkflowDevelopmentRole-streamlit

  CDKDeploy:
    Identifier: aws/cdk-deploy@v1
    DependsOn:
      - InstallDependencies
      - CDKBootstrap
    Timeout: 15
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      StackName: streamlit-app-stack
      Region: us-east-1
      Context: '{"stack_name": "streamlit-app-stack"}'
    Environment:
      Name: default_environment
      Connections:
        - Name: "536697236057"
          Role: CodeCatalystWorkflowDevelopmentRole-streamlit
    Outputs:
      Artifacts:
        - Name: CDKDeploymentOutput
          Files:
            - cdk.out/*

  PostDeploy:
    Identifier: aws/lambda-invoke@v1
    DependsOn:
      - CDKDeploy
    Timeout: 5
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    Configuration:
      FunctionName: "post-deploy"
      Payload: |
        {
          "commands": [
            "aws cloudformation describe-stacks --stack-name streamlit-app-stack --query \"Stacks[0].Outputs[?OutputKey=='CloudFrontURL'].OutputValue\" --output text",
            "aws cloudformation describe-stacks --stack-name streamlit-app-stack --query \"Stacks[0].Outputs[?OutputKey=='CognitoUserPoolId'].OutputValue\" --output text"
          ]
        }
