Name: streamlitDeploymentPipeline
SchemaVersion: "1.0"

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:
  InstallDependencies:
    Identifier: aws/codebuild@v1
    Timeout: 10
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      ProjectName: "InstallDependencies"
      BuildSpec: |
        version: 0.2
        phases:
          install:
            runtime-versions:
              python: 3.9
            commands:
              - echo "Instalando dependencias..."
              - python -m venv .venv
              - source .venv/bin/activate
              - pip install -r requirements.txt

  CDKBootstrap:
    Identifier: aws/cdk-bootstrap@v1
    Timeout: 10
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      Region: us-east-1
    Environment:
      Name: default_environment
      Connections:
        - Name: "536697236057"
          Role: CodeCatalystWorkflowDevelopmentRole-streamlit

  CDKDeploy:
    Identifier: aws/cdk-deploy@v1
    DependsOn:
      - InstallDependencies
      - CDKBootstrap
    Timeout: 15
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      StackName: streamlit-app-stack
      Region: us-east-1
      Context: '{"stack_name": "streamlit-app-stack"}'
    Environment:
      Name: default_environment
      Connections:
        - Name: "536697236057"
          Role: CodeCatalystWorkflowDevelopmentRole-streamlit
    Outputs:
      Artifacts:
        - Name: CDKDeploymentOutput
          Files:
            - cdk.out/*

  PostDeploy:
    Identifier: aws/codebuild@v1
    DependsOn:
      - CDKDeploy
    Timeout: 5
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    Configuration:
      ProjectName: "PostDeploy"
      BuildSpec: |
        version: 0.2
        phases:
          build:
            commands:
              - echo "Obteniendo URL de CloudFront y User Pool ID..."
              - DISTRIBUTION_URL=$(aws cloudformation describe-stacks --stack-name streamlit-app-stack --query "Stacks[0].Outputs[?OutputKey=='CloudFrontURL'].OutputValue" --output text)
              - USER_POOL_ID=$(aws cloudformation describe-stacks --stack-name streamlit-app-stack --query "Stacks[0].Outputs[?OutputKey=='CognitoUserPoolId'].OutputValue" --output text)
              - echo "URL de CloudFront: $DISTRIBUTION_URL"
              - echo "ID de User Pool de Cognito: $USER_POOL_ID"
