Name: streamlitDeploymentPipeline
SchemaVersion: "1.0"

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:

  CDKBootstrap:
    Identifier: aws/cdk-bootstrap@v2.0.1
    Environment:
      Connections:
        - Role: CodeCatalystWorkflowDevelopmentRole-workshop-devops
          Name: "536697236057"
      Name: default_environment
    Timeout: 10
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: EC2
    Configuration:
      Region: us-east-1
      CdkCliVersion: 2.160.0

  CDKDeploy:
    Identifier: aws/cdk-deploy@v2.0.2
    Outputs:
      Artifacts:
        - Name: CDKDeploymentOutput
          Files:
            - cdk.out/*
    Environment:
      Connections:
        - Role: CodeCatalystWorkflowDevelopmentRole-workshop-devops
          Name: "536697236057"
      Name: default_environment
    Timeout: 15
    Inputs:
      Sources:
        - WorkflowSource
    Compute:
      Type: EC2
    Configuration:
      StackName: streamlit-app-stack
      Region: us-east-1
      CdkCliVersion: 2.160.0
      Context: '{"stack_name":"streamlit-app-stack"}'
    DependsOn:
      - CDKBootstrap
