Name: streamlitDeploymentPipeline
SchemaVersion: "1.0"

Triggers:
  - Type: PUSH
    Branches:
      - main

Actions:
  CDKBootstrap:
    Identifier: aws/cdk-bootstrap@v2.0.1
    Timeout: 10
    Compute:
      Type: EC2
      Fleet: Linux.x86-64.Large
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      Region: us-east-1

  CDKDeploy:
    Identifier: aws/cdk-deploy@v2.0.2
    DependsOn:
      - CDKBootstrap
    Timeout: 15
    Inputs:
      Sources:
        - WorkflowSource
    Configuration:
      StackName: streamlit-app-stack
      Region: us-east-1
      Context: '{"stack_name": "streamlit-app-stack"}'
    Outputs:
      Artifacts:
        - Name: CDKDeploymentOutput
          Files:
            - cdk.out/*
